/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HillNavbar {
        "bgColor": any;
        "hasRoundedCorners": boolean;
        "homeLinkImageUrl": string;
        "homeLinkText": string;
        "homeLinkUrl": string;
        "isNightMode": boolean;
        "menuList": Array<string>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLHillNavbarElement extends Components.HillNavbar, HTMLStencilElement {
    }
    var HTMLHillNavbarElement: {
        prototype: HTMLHillNavbarElement;
        new (): HTMLHillNavbarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "hill-navbar": HTMLHillNavbarElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface HillNavbar {
        "bgColor"?: any;
        "hasRoundedCorners"?: boolean;
        "homeLinkImageUrl"?: string;
        "homeLinkText"?: string;
        "homeLinkUrl"?: string;
        "isNightMode"?: boolean;
        "menuList"?: Array<string>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "hill-navbar": HillNavbar;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hill-navbar": LocalJSX.HillNavbar & JSXBase.HTMLAttributes<HTMLHillNavbarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
